logging:
  LOGGER_NAME: 'root'


load_data:
  train_file: "Data/amazon_review_full_csv/train.csv"
  test_file: "Data/amazon_review_full_csv/test.csv"

summary_stats:
  save_location: "Outputs/"

models:
  save_location: "Models/"